project_name: gomigemo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: gomigemo
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - 386
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: mac
      linux: linux
      windows: windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto