project_name: gomigemo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: gomigemo
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - 386
      - amd64
archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: mac
      linux: linux
      windows: windows
      386: 32bit
      amd64: 64bit
    format: zip
release:
  prerelease: auto